package shafin.nlp.util;

import java.util.ArrayList;
import java.util.List;

public class FMeasure {

	public static double generatePrecision(List<String> manualKP, List<String> systemKP) {
		int K = systemKP.size();// K = number of KP generated by the system
		int N = 0;// N = number of KP matched
		for (String kp : systemKP) {
			if (manualKP.contains(kp)) {
				N++;
			}
		}
		return (double)N/K;
	}

	public static double generateRecall(List<String> manualKP, List<String> systemKP) {
		int M = manualKP.size();// K = number of KP assigned manually
		int N = 0;// N = number of KP matched
		for (String kp : systemKP) {
			if (manualKP.contains(kp)) {
				N++;
			}
		}
		return (double)N/M;
	}
	
	
	public static void main(String[] args) {
		List<String> manualKP = new ArrayList<>();
		List<String> systemKP = new ArrayList<>();
		
		manualKP.add("SUST");
		manualKP.add("CSE");
		manualKP.add("shafin");
		manualKP.add("2011");
		manualKP.add("Sylhet");
		
		systemKP.add("CSE");
		systemKP.add("FET");
		systemKP.add("Tong");
		systemKP.add("Sylhet");
		
		System.out.println("precision: "+generatePrecision(manualKP, systemKP));
		System.out.println("recall: "+generateRecall(manualKP, systemKP));
	}
}
